const citiesOfArgentina = [
  // ARGENTINA
  "25 de Mayo",
  "9 de Julio",
  "Aguilares",
  "Allen",
  "Alta Gracia",
  "Añatuya",
  "Apóstoles",
  "Arrecifes",
  "Arroyito",
  "Arroyo Seco",
  "Azul",
  "Bahía Blanca",
  "Balcarce",
  "Baradero",
  "Bella Vista",
  "Bell Ville",
  "Bragado",
  "Buenos Aires",
  "Caleta Olivia",
  "Campana",
  "Cañada de Gómez",
  "Cañuelas",
  "Casilda",
  "Catamarca",
  "Catriel",
  "Caucete",
  "Centenario",
  "Chacabuco",
  "Chajarí",
  "Charata",
  "Chascomús",
  "Chilecito",
  "Chivilcoy",
  "Cinco Saltos",
  "Clorinda",
  "Colón",
  "Colonia Caroya",
  "Comodoro Rivadavia",
  "Concepción",
  "Concepción del Uruguay",
  "Concordia",
  "Córdoba",
  "Coronel Brandsen",
  "Coronel Pringles",
  "Coronel Suárez",
  "Corrientes",
  "Cosquín",
  "Crespo",
  "Cruz del Eje",
  "Curuzú Cuatiá",
  "Cutral Có",
  "Deán Funes",
  "Delfín Gallo",
  "Diamante",
  "Dolores",
  "El Bolsón",
  "El Calafate",
  "Eldorado",
  "Embarcación",
  "Esperanza",
  "Esquel",
  "Esquina",
  "Famaillá",
  "Federación",
  "Firmat",
  "Formosa",
  "Frías",
  "Gálvez",
  "General Alvear",
  "General Güemes",
  "General Pico",
  "General Roca",
  "General San Martín",
  "Gobernador Virasoro",
  "Goya",
  "Gualeguay",
  "Gualeguaychú",
  "Ituzaingó",
  "Jardín América",
  "Jesús María",
  "Juan Bautista Alberdi",
  "Juan José Castelli",
  "Junín",
  "Laboulaye",
  "La Falda",
  "La Paz",
  "La Plata",
  "La Quiaca",
  "La Rioja",
  "Las Breñas",
  "Las Flores",
  "Las Heras",
  "Leandro N. Alem",
  "Libertador General San Martín",
  "Lincoln",
  "Lobos",
  "Luján",
  "Lules",
  "Machagai",
  "Malargüe",
  "Marcos Juárez",
  "Mar de Ajó",
  "Mar del Plata",
  "Mendoza",
  "Mercedes",
  "Merlo",
  "Miramar",
  "Montecarlo",
  "Monte Caseros",
  "Monteros",
  "Necochea",
  "Neuquén",
  "Nogoyá",
  "Oberá",
  "Olavarría",
  "Paraná",
  "Paso de los Libres",
  "Pehuajó",
  "Pergamino",
  "Perico",
  "Pichanal",
  "Pico Truncado",
  "Pinamar",
  "Pirané",
  "Posadas",
  "Presidencia Roque Sáenz Peña",

  "Profesor Salvador Mazza",
  "Puerto Iguazú",
  "Puerto Madryn",
  "Punta Alta",
  "Quitilipi",
  "Rafaela",

  "Rawson",
  "Reconquista",
  "Resistencia",
  "Rincón de los Sauces",
  "Río Cuarto",
  "Río Gallegos",
  "Río Grande",
  "Río Segundo",
  "Río Tercero",
  "Rivadavia",
  "Rojas",
  "Rosario",
  "Rosario de la Frontera",
  "Rosario de Lerma",
  "Rufino",
  "Saladillo",
  "Salta",
  "Salto",
  "San Antonio de Areco",
  "San Antonio Oeste",
  "San Carlos de Bariloche",
  "San Carlos de Bolívar",
  "San Francisco",
  "San José",
  "San José de Metán",
  "San Juan",
  "San Justo",
  "San Luis",
  "San Martín",
  "San Martín de los Andes",
  "San Miguel de Tucumán",
  "San Nicolás de los Arroyos",
  "San Pedro",
  "San Pedro de Jujuy",
  "San Rafael",
  "San Ramón de la Nueva Orán",
  "San Salvador de Jujuy",
  "Santa Fe",
  "Santa Rosa de Toay",
  "Santa Teresita",
  "Santiago del Estero",
  "Santo Tomé",
  "San Vicente",
  "Sunchales",
  "Tafí Viejo",
  "Tandil",
  "Tartagal",
  "Termas de Río Hondo",
  "Trelew",
  "Trenque Lauquen",
  "Tres Arroyos",
  "Tunuyán",
  "Ushuaia",
  "Venado Tuerto",
  "Vera",
  "Victoria",
  "Viedma",
  "Villa Aberastain",
  "Villa Ángela",
  "Villa Carlos Paz",
  "Villa Constitución",
  "Villa Dolores",
  "Villa General San Martín",
  "Villa Gesell",
  "Villaguay",
  "Villa María",
  "Villa Mercedes",
  "Villa Regina",
  "Zapala",
  "Zárate",
];

export const authorizedCities = [...citiesOfArgentina];
